# Generated by Django 3.0.6 on 2020-05-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimQueryTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='FactDeliveryTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start', models.DateTimeField(verbose_name='slot_start')),
                ('slot_end', models.DateTimeField(verbose_name='slot_end')),
                ('price', models.FloatField(verbose_name='price')),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerapi.DimQueryTime')),
            ],
        ),
    ]
