# Generated by Django 3.0.6 on 2020-05-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdeliverytime',
            name='price',
            field=models.FloatField(null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='factdeliverytime',
            name='slot_end',
            field=models.DateTimeField(null=True, verbose_name='slot_end'),
        ),
        migrations.AlterField(
            model_name='factdeliverytime',
            name='slot_start',
            field=models.DateTimeField(null=True, verbose_name='slot_start'),
        ),
    ]
